/* DO NOT EDIT: automatically built by dist/s_include. */
#ifndef	_db_ext_h_
#define	_db_ext_h_

#if defined(__cplusplus)
extern "C" {
#endif

gint __crdel_metasub_log __P((DB *, DB_TXN *, DB_LSN *, u_int32_t, db_pgno_t, const DBT *, DB_LSN *));
gint __crdel_metasub_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __crdel_metasub_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __crdel_metasub_read __P((DB_ENV *, gpointer , __crdel_metasub_args **));
gint __crdel_init_print __P((DB_ENV *, gint (***)(DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ), size_t *));
gint __crdel_init_getpgnos __P((DB_ENV *, gint (***)(DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ), size_t *));
gint __crdel_init_recover __P((DB_ENV *, gint (***)(DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ), size_t *));
gint __crdel_metasub_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_master_open __P((DB *, DB_TXN *, const gchar *, u_int32_t, int, DB **));
gint __db_master_update __P((DB *, DB *, DB_TXN *, const gchar *, DBTYPE, mu_action, const gchar *, u_int32_t));
gint __db_dbenv_setup __P((DB *, DB_TXN *, const gchar *, u_int32_t, u_int32_t));
gint __db_close __P((DB *, u_int32_t));
gint __db_close_i __P((DB *, DB_TXN *, u_int32_t));
gint __db_refresh __P((DB *, DB_TXN *, u_int32_t));
gint __db_log_page __P((DB *, DB_TXN *, DB_LSN *, db_pgno_t, PAGE *));
gint __db_backup_name __P((DB_ENV *, const gchar *, DB_TXN *, gchar **));
DB *__dblist_get __P((DB_ENV *, u_int32_t));
#if CONFIG_TEST
gint __db_testcopy __P((DB_ENV *, DB *, const gchar *));
#endif
gint __db_cursor __P((DB *, DB_TXN *, DBC **, u_int32_t));
gint __db_icursor __P((DB *, DB_TXN *, DBTYPE, db_pgno_t, int, u_int32_t, DBC **));
gint __db_cprint __P((DB *));
gint __db_fd __P((DB *, gint *));
gint __db_get __P((DB *, DB_TXN *, DBT *, DBT *, u_int32_t));
gint __db_put __P((DB *, DB_TXN *, DBT *, DBT *, u_int32_t));
gint __db_delete __P((DB *, DB_TXN *, DBT *, u_int32_t));
gint __db_sync __P((DB *, u_int32_t));
gint __db_associate __P((DB *, DB_TXN *, DB *, gint (*)(DB *, const DBT *, const DBT *, DBT *), u_int32_t));
gint __db_pget __P((DB *, DB_TXN *, DBT *, DBT *, DBT *, u_int32_t));
gint __db_addrem_log __P((DB *, DB_TXN *, DB_LSN *, u_int32_t, u_int32_t, db_pgno_t, u_int32_t, u_int32_t, const DBT *, const DBT *, DB_LSN *));
gint __db_addrem_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_addrem_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_addrem_read __P((DB_ENV *, gpointer , __db_addrem_args **));
gint __db_big_log __P((DB *, DB_TXN *, DB_LSN *, u_int32_t, u_int32_t, db_pgno_t, db_pgno_t, db_pgno_t, const DBT *, DB_LSN *, DB_LSN *, DB_LSN *));
gint __db_big_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_big_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_big_read __P((DB_ENV *, gpointer , __db_big_args **));
gint __db_ovref_log __P((DB *, DB_TXN *, DB_LSN *, u_int32_t, db_pgno_t, int32_t, DB_LSN *));
gint __db_ovref_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_ovref_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_ovref_read __P((DB_ENV *, gpointer , __db_ovref_args **));
gint __db_relink_log __P((DB *, DB_TXN *, DB_LSN *, u_int32_t, u_int32_t, db_pgno_t, DB_LSN *, db_pgno_t, DB_LSN *, db_pgno_t, DB_LSN *));
gint __db_relink_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_relink_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_relink_read __P((DB_ENV *, gpointer , __db_relink_args **));
gint __db_debug_log __P((DB_ENV *, DB_TXN *, DB_LSN *, u_int32_t, const DBT *, int32_t, const DBT *, const DBT *, u_int32_t));
gint __db_debug_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_debug_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_debug_read __P((DB_ENV *, gpointer , __db_debug_args **));
gint __db_noop_log __P((DB *, DB_TXN *, DB_LSN *, u_int32_t, db_pgno_t, DB_LSN *));
gint __db_noop_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_noop_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_noop_read __P((DB_ENV *, gpointer , __db_noop_args **));
gint __db_pg_alloc_log __P((DB *, DB_TXN *, DB_LSN *, u_int32_t, DB_LSN *, db_pgno_t, DB_LSN *, db_pgno_t, u_int32_t, db_pgno_t));
gint __db_pg_alloc_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_pg_alloc_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_pg_alloc_read __P((DB_ENV *, gpointer , __db_pg_alloc_args **));
gint __db_pg_free_log __P((DB *, DB_TXN *, DB_LSN *, u_int32_t, db_pgno_t, DB_LSN *, db_pgno_t, const DBT *, db_pgno_t));
gint __db_pg_free_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_pg_free_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_pg_free_read __P((DB_ENV *, gpointer , __db_pg_free_args **));
gint __db_cksum_log __P((DB_ENV *, DB_TXN *, DB_LSN *, u_int32_t));
gint __db_cksum_getpgnos __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_cksum_print __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_cksum_read __P((DB_ENV *, gpointer , __db_cksum_args **));
gint __db_init_print __P((DB_ENV *, gint (***)(DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ), size_t *));
gint __db_init_getpgnos __P((DB_ENV *, gint (***)(DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ), size_t *));
gint __db_init_recover __P((DB_ENV *, gint (***)(DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ), size_t *));
gint __db_c_close __P((DBC *));
gint __db_c_destroy __P((DBC *));
gint __db_c_count __P((DBC *, db_recno_t *, u_int32_t));
gint __db_c_del __P((DBC *, u_int32_t));
gint __db_c_dup __P((DBC *, DBC **, u_int32_t));
gint __db_c_idup __P((DBC *, DBC **, u_int32_t));
gint __db_c_newopd __P((DBC *, db_pgno_t, DBC *, DBC **));
gint __db_c_get __P((DBC *, DBT *, DBT *, u_int32_t));
gint __db_c_put __P((DBC *, DBT *, DBT *, u_int32_t));
gint __db_duperr __P((DB *, u_int32_t));
gint __db_c_secondary_get __P((DBC *, DBT *, DBT *, u_int32_t));
gint __db_c_pget __P((DBC *, DBT *, DBT *, DBT *, u_int32_t));
gint __db_c_del_primary __P((DBC *));
DB *__db_s_first __P((DB *));
gint __db_s_next __P((DB **));
gint __db_s_done __P((DB *));
u_int32_t __db_partsize __P((u_int32_t, DBT *));
gint __db_pgin __P((DB_ENV *, db_pgno_t, gpointer , DBT *));
gint __db_pgout __P((DB_ENV *, db_pgno_t, gpointer , DBT *));
void __db_metaswap __P((PAGE *));
gint __db_byteswap __P((DB_ENV *, DB *, db_pgno_t, PAGE *, size_t, int));
gint __db_dispatch __P((DB_ENV *, gint (**)__P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer )), size_t, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_add_recovery __P((DB_ENV *, gint (***)(DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ), size_t *, gint (*)(DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ), u_int32_t));
gint __db_txnlist_init __P((DB_ENV *, u_int32_t, u_int32_t, DB_LSN *, gpointer ));
gint __db_txnlist_add __P((DB_ENV *, gpointer , u_int32_t, int32_t, DB_LSN *));
gint __db_txnlist_remove __P((DB_ENV *, gpointer , u_int32_t));
void __db_txnlist_ckp __P((DB_ENV *, gpointer , DB_LSN *));
void __db_txnlist_end __P((DB_ENV *, gpointer ));
gint __db_txnlist_find __P((DB_ENV *, gpointer , u_int32_t));
gint __db_txnlist_update __P((DB_ENV *, gpointer , u_int32_t, u_int32_t, DB_LSN *));
gint __db_txnlist_gen __P((DB_ENV *, gpointer , int, u_int32_t, u_int32_t));
gint __db_txnlist_lsnadd __P((DB_ENV *, gpointer , DB_LSN *, u_int32_t));
gint __db_txnlist_lsninit __P((DB_ENV *, DB_TXNHEAD *, DB_LSN *));
gint __db_add_limbo __P((DB_ENV *, gpointer , int32_t, db_pgno_t, int32_t));
gint __db_do_the_limbo __P((DB_ENV *, DB_TXN *, DB_TXN *, DB_TXNHEAD *));
void __db_txnlist_print __P((gpointer));
gint __db_ditem __P((DBC *, PAGE *, u_int32_t, u_int32_t));
gint __db_pitem __P((DBC *, PAGE *, u_int32_t, u_int32_t, DBT *, DBT *));
gint __db_relink __P((DBC *, u_int32_t, PAGE *, PAGE **, int));
gint __db_cursorchk __P((const DB *, u_int32_t));
gint __db_ccountchk __P((const DB *, u_int32_t, int));
gint __db_cdelchk __P((const DB *, u_int32_t, int));
gint __db_cgetchk __P((const DB *, DBT *, DBT *, u_int32_t, int));
gint __db_cputchk __P((const DB *, const DBT *, DBT *, u_int32_t, int));
gint __db_pgetchk __P((const DB *, const DBT *, DBT *, DBT *, u_int32_t));
gint __db_cpgetchk __P((const DB *, DBT *, DBT *, DBT *, u_int32_t, int));
gint __db_delchk __P((const DB *, DBT *, u_int32_t));
gint __db_getchk __P((const DB *, const DBT *, DBT *, u_int32_t));
gint __db_joinchk __P((const DB *, DBC * const *, u_int32_t));
gint __db_joingetchk __P((const DB *, DBT *, u_int32_t));
gint __db_putchk __P((const DB *, DBT *, const DBT *, u_int32_t, int));
gint __db_statchk __P((const DB *, u_int32_t));
gint __db_syncchk __P((const DB *, u_int32_t));
gint __db_secondary_corrupt __P((DB *));
gint __db_associatechk __P((DB *, DB *, gint (*)(DB *, const DBT *, const DBT *, DBT *), u_int32_t));
gint __db_txn_auto __P((DB *, DB_TXN **));
gint __db_join __P((DB *, DBC **, DBC **, u_int32_t));
gint __db_new __P((DBC *, u_int32_t, PAGE **));
gint __db_free __P((DBC *, PAGE *));
gint __db_lprint __P((DBC *));
gint __db_lget __P((DBC *, int, db_pgno_t, db_lockmode_t, u_int32_t, DB_LOCK *));
gint __db_lput __P((DBC *, DB_LOCK *));
gint __dbh_am_chk __P((DB *, u_int32_t));
gint  __db_set_lorder __P((DB *, int));
gint __db_open __P((DB *, DB_TXN *, const gchar *, const gchar *, DBTYPE, u_int32_t, int));
gint __db_dbopen __P((DB *, DB_TXN *, const gchar *, const gchar *, u_int32_t, int, db_pgno_t));
gint __db_new_file __P((DB *, DB_TXN *, DB_FH *, const gchar *));
gint __db_init_subdb __P((DB *, DB *, const gchar *, DB_TXN *));
gint __db_chk_meta __P((DB_ENV *, DB *, DBMETA *, int));
gint __db_meta_setup __P((DB_ENV *, DB *, const gchar *, DBMETA *, u_int32_t, int));
gint __db_goff __P((DB *, DBT *, u_int32_t, db_pgno_t, gpointer *, u_int32_t *));
gint __db_poff __P((DBC *, const DBT *, db_pgno_t *));
gint __db_ovref __P((DBC *, db_pgno_t, int32_t));
gint __db_doff __P((DBC *, db_pgno_t));
gint __db_moff __P((DB *, const DBT *, db_pgno_t, u_int32_t, gint (*)(DB *, const DBT *, const DBT *), gint *));
gint __db_vrfy_overflow __P((DB *, VRFY_DBINFO *, PAGE *, db_pgno_t, u_int32_t));
gint __db_vrfy_ovfl_structure __P((DB *, VRFY_DBINFO *, db_pgno_t, u_int32_t, u_int32_t));
gint __db_safe_goff __P((DB *, VRFY_DBINFO *, db_pgno_t, DBT *, gpointer *, u_int32_t));
void __db_loadme __P((void));
gint __db_dump __P((DB *, gchar *, gchar *));
void __db_inmemdbflags __P((u_int32_t, gpointer , void (*)(u_int32_t, const FN *, gpointer )));
gint __db_prnpage __P((DB *, db_pgno_t, FILE *));
gint __db_prpage __P((DB *, PAGE *, FILE *, u_int32_t));
void __db_pr __P((u_int8_t *, u_int32_t, FILE *));
gint __db_prdbt __P((DBT *, int, const gchar *, gpointer , gint (*)(gpointer , gconstpointer ), int, VRFY_DBINFO *));
void __db_prflags __P((u_int32_t, const FN *, gpointer ));
const gchar * __db_dbtype_to_string __P((DBTYPE));
int	__db_prheader __P((DB *, gchar *, int, int, gpointer , gint (*)(gpointer , gconstpointer ), VRFY_DBINFO *, db_pgno_t));
gint __db_prfooter __P((gpointer , gint (*)(gpointer , gconstpointer )));
gint __db_addrem_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_big_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_ovref_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_relink_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_debug_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_noop_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_pg_alloc_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_pg_free_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_cksum_recover __P((DB_ENV *, DBT *, DB_LSN *, db_recops, gpointer ));
gint __db_traverse_big __P((DB *, db_pgno_t, gint (*)(DB *, PAGE *, gpointer , gint *), gpointer ));
gint __db_reclaim_callback __P((DB *, PAGE *, gpointer , gint *));
gint __db_truncate_callback __P((DB *, PAGE *, gpointer , gint *));
gint __dbenv_dbremove __P((DB_ENV *, DB_TXN *, const gchar *, const gchar *, u_int32_t));
gint __db_remove __P((DB *, const gchar *, const gchar *, u_int32_t));
gint __db_remove_i __P((DB *, DB_TXN *, const gchar *, const gchar *));
gint __dbenv_dbrename __P((DB_ENV *, DB_TXN *, const gchar *, const gchar *, const gchar *, u_int32_t));
gint __db_rename __P((DB *, const gchar *, const gchar *, const gchar *, u_int32_t));
gint __db_rename_i __P((DB *, DB_TXN *, const gchar *, const gchar *, const gchar *));
gint __db_ret __P((DB *, PAGE *, u_int32_t, DBT *, gpointer *, u_int32_t *));
gint __db_retcopy __P((DB_ENV *, DBT *, gpointer , u_int32_t, gpointer *, u_int32_t *));
gint __db_truncate __P((DB *, DB_TXN *, u_int32_t *, u_int32_t));
gint __db_upgrade __P((DB *, const gchar *, u_int32_t));
gint __db_lastpgno __P((DB *, gchar *, DB_FH *, db_pgno_t *));
gint __db_31_offdup __P((DB *, gchar *, DB_FH *, int, db_pgno_t *));
gint __db_verify __P((DB *, const gchar *, const gchar *, FILE *, u_int32_t));
gint  __db_verify_callback __P((gpointer , gconstpointer ));
gint __db_verify_internal __P((DB *, const gchar *, const gchar *, gpointer , gint (*)(gpointer , gconstpointer ), u_int32_t));
gint __db_vrfy_datapage __P((DB *, VRFY_DBINFO *, PAGE *, db_pgno_t, u_int32_t));
gint __db_vrfy_meta __P((DB *, VRFY_DBINFO *, DBMETA *, db_pgno_t, u_int32_t));
void __db_vrfy_struct_feedback __P((DB *, VRFY_DBINFO *));
gint __db_vrfy_inpitem __P((DB *, PAGE *, db_pgno_t, u_int32_t, int, u_int32_t, u_int32_t *, u_int32_t *));
gint __db_vrfy_duptype __P((DB *, VRFY_DBINFO *, db_pgno_t, u_int32_t));
gint __db_salvage_duptree __P((DB *, VRFY_DBINFO *, db_pgno_t, DBT *, gpointer , gint (*)(gpointer , gconstpointer ), u_int32_t));
gint __db_vrfy_dbinfo_create __P((DB_ENV *, u_int32_t, VRFY_DBINFO **));
gint __db_vrfy_dbinfo_destroy __P((DB_ENV *, VRFY_DBINFO *));
gint __db_vrfy_getpageinfo __P((VRFY_DBINFO *, db_pgno_t, VRFY_PAGEINFO **));
gint __db_vrfy_putpageinfo __P((DB_ENV *, VRFY_DBINFO *, VRFY_PAGEINFO *));
gint __db_vrfy_pgset __P((DB_ENV *, u_int32_t, DB **));
gint __db_vrfy_pgset_get __P((DB *, db_pgno_t, gint *));
gint __db_vrfy_pgset_inc __P((DB *, db_pgno_t));
gint __db_vrfy_pgset_dec __P((DB *, db_pgno_t));
gint __db_vrfy_pgset_next __P((DBC *, db_pgno_t *));
gint __db_vrfy_childcursor __P((VRFY_DBINFO *, DBC **));
gint __db_vrfy_childput __P((VRFY_DBINFO *, db_pgno_t, VRFY_CHILDINFO *));
gint __db_vrfy_ccset __P((DBC *, db_pgno_t, VRFY_CHILDINFO **));
gint __db_vrfy_ccnext __P((DBC *, VRFY_CHILDINFO **));
gint __db_vrfy_ccclose __P((DBC *));
gint  __db_salvage_init __P((VRFY_DBINFO *));
void  __db_salvage_destroy __P((VRFY_DBINFO *));
gint __db_salvage_getnext __P((VRFY_DBINFO *, db_pgno_t *, u_int32_t *));
gint __db_salvage_isdone __P((VRFY_DBINFO *, db_pgno_t));
gint __db_salvage_markdone __P((VRFY_DBINFO *, db_pgno_t));
gint __db_salvage_markneeded __P((VRFY_DBINFO *, db_pgno_t, u_int32_t));

#if defined(__cplusplus)
}
#endif
#endif /* !_db_ext_h_ */
