/* File:       e-gdbus-typemappers.h
 *
 * Generated by GDBus Binding Tool 0.1. DO NOT EDIT.
 */

#ifndef __E_GDBUS_TYPE_MAPPERS_H__
#define __E_GDBUS_TYPE_MAPPERS_H__

#include <gio/gio.h>

#endif /* __E_GDBUS_TYPE_MAPPERS_H__ */
