/*
 * Generated by gdbus-codegen.py 0.1. DO NOT EDIT.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "e-gdbus-emailstore.h"

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  GParamSpec *pspec;
  GValue value;
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    goto out;
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

#include <ffi.h>
static ffi_type *
value_to_ffi_type (const GValue *gvalue, gpointer *value)
{
  ffi_type *rettype = NULL;
  GType type = g_type_fundamental (G_VALUE_TYPE (gvalue));
  g_assert (type != G_TYPE_INVALID);

  switch (type)
    {
    case G_TYPE_BOOLEAN:
    case G_TYPE_CHAR:
    case G_TYPE_INT:
      rettype = &ffi_type_sint;
      *value = (gpointer)&(gvalue->data[0].v_int);
      break;
    case G_TYPE_UCHAR:
    case G_TYPE_UINT:
      rettype = &ffi_type_uint;
      *value = (gpointer)&(gvalue->data[0].v_uint);
      break;
    case G_TYPE_STRING:
    case G_TYPE_OBJECT:
    case G_TYPE_BOXED:
    case G_TYPE_POINTER:
    case G_TYPE_INTERFACE:
    case G_TYPE_VARIANT:
      rettype = &ffi_type_pointer;
      *value = (gpointer)&(gvalue->data[0].v_pointer);
      break;
    case G_TYPE_FLOAT:
      rettype = &ffi_type_float;
      *value = (gpointer)&(gvalue->data[0].v_float);
      break;
    case G_TYPE_DOUBLE:
      rettype = &ffi_type_double;
      *value = (gpointer)&(gvalue->data[0].v_double);
      break;
    case G_TYPE_LONG:
      rettype = &ffi_type_slong;
      *value = (gpointer)&(gvalue->data[0].v_long);
      break;
    case G_TYPE_ULONG:
      rettype = &ffi_type_ulong;
      *value = (gpointer)&(gvalue->data[0].v_ulong);
      break;
    case G_TYPE_INT64:
      rettype = &ffi_type_sint64;
      *value = (gpointer)&(gvalue->data[0].v_int64);
      break;
    case G_TYPE_UINT64:
      rettype = &ffi_type_uint64;
      *value = (gpointer)&(gvalue->data[0].v_uint64);
      break;
    default:
      rettype = &ffi_type_pointer;
      *value = NULL;
      g_warning ("value_to_ffi_type: Unsupported fundamental type: %s", g_type_name (type));
      break;
    }
  return rettype;
}

static void
value_from_ffi_type (GValue *gvalue, gpointer *value)
{
  switch (g_type_fundamental (G_VALUE_TYPE (gvalue)))
    {
    case G_TYPE_INT:
      g_value_set_int (gvalue, *(gint*)value);
      break;
    case G_TYPE_FLOAT:
      g_value_set_float (gvalue, *(gfloat*)value);
      break;
    case G_TYPE_DOUBLE:
      g_value_set_double (gvalue, *(gdouble*)value);
      break;
    case G_TYPE_BOOLEAN:
      g_value_set_boolean (gvalue, *(gboolean*)value);
      break;
    case G_TYPE_STRING:
      g_value_set_string (gvalue, *(gchar**)value);
      break;
    case G_TYPE_CHAR:
      g_value_set_char (gvalue, *(gchar*)value);
      break;
    case G_TYPE_UCHAR:
      g_value_set_uchar (gvalue, *(guchar*)value);
      break;
    case G_TYPE_UINT:
      g_value_set_uint (gvalue, *(guint*)value);
      break;
    case G_TYPE_POINTER:
      g_value_set_pointer (gvalue, *(gpointer*)value);
      break;
    case G_TYPE_LONG:
      g_value_set_long (gvalue, *(glong*)value);
      break;
    case G_TYPE_ULONG:
      g_value_set_ulong (gvalue, *(gulong*)value);
      break;
    case G_TYPE_INT64:
      g_value_set_int64 (gvalue, *(gint64*)value);
      break;
    case G_TYPE_UINT64:
      g_value_set_uint64 (gvalue, *(guint64*)value);
      break;
    case G_TYPE_BOXED:
      g_value_set_boxed (gvalue, *(gpointer*)value);
      break;
    default:
      g_warning ("value_from_ffi_type: Unsupported fundamental type: %s",
                g_type_name (g_type_fundamental (G_VALUE_TYPE (gvalue))));
    }
}

static void
_cclosure_marshal_generic (GClosure *closure,
                             GValue *return_gvalue,
                             guint n_param_values,
                             const GValue *param_values,
                             gpointer invocation_hint,
                             gpointer marshal_data)
{
  ffi_type *rtype;
  void *rvalue;
  int n_args;
  ffi_type **atypes;
  void **args;
  int i;
  ffi_cif cif;
  GCClosure *cc = (GCClosure*) closure;

  if (return_gvalue && G_VALUE_TYPE (return_gvalue)) 
    {
      rtype = value_to_ffi_type (return_gvalue, &rvalue);
    }
  else 
    {
      rtype = &ffi_type_void;
    }

  rvalue = g_alloca (MAX (rtype->size, sizeof (ffi_arg)));
  
  n_args = n_param_values + 1;
  atypes = g_alloca (sizeof (ffi_type *) * n_args);
  args =  g_alloca (sizeof (gpointer) * n_args);

  if (G_CCLOSURE_SWAP_DATA (closure))
    {
      atypes[n_args-1] = value_to_ffi_type (param_values + 0,  
                                            &args[n_args-1]);
      atypes[0] = &ffi_type_pointer;
      args[0] = &closure->data;
    }
  else
    {
      atypes[0] = value_to_ffi_type (param_values + 0, &args[0]);
      atypes[n_args-1] = &ffi_type_pointer;
      args[n_args-1] = &closure->data;
    }

  for (i = 1; i < n_args - 1; i++)
    atypes[i] = value_to_ffi_type (param_values + i, &args[i]);

  if (ffi_prep_cif (&cif, FFI_DEFAULT_ABI, n_args, rtype, atypes) != FFI_OK)
    return;

  ffi_call (&cif, marshal_data ? marshal_data : cc->callback, rvalue, args);

  if (return_gvalue && G_VALUE_TYPE (return_gvalue))
    value_from_ffi_type (return_gvalue, rvalue);
}

/* ------------------------------------------------------------------------
 * Code for interface org.gnome.evolution.dataserver.mail.Store
 * ------------------------------------------------------------------------
 */

/* ---- Introspection data for org.gnome.evolution.dataserver.mail.Store ---- */

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_get_folder_IN_ARG_full_name =
{
  {
    -1,
    "full_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_get_folder_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_get_folder_IN_ARG_full_name,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_get_folder_OUT_ARG_folder =
{
  {
    -1,
    "folder",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_get_folder_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_get_folder_OUT_ARG_folder,
  NULL
};

static const GDBusAnnotationInfo _egdbus_store_ms_method_get_folder_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.CSymbol",
  "impl_Mail_Store_getFolder",
  NULL
};

static const GDBusAnnotationInfo _egdbus_store_ms_method_get_folder_annotation_info_1 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "",
  NULL
};

static const GDBusAnnotationInfo * const _egdbus_store_ms_method_get_folder_annotation_info_pointers[] =
{
  &_egdbus_store_ms_method_get_folder_annotation_info_0,
  &_egdbus_store_ms_method_get_folder_annotation_info_1,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_get_folder =
{
  {
    -1,
    "getFolder",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_get_folder_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_get_folder_OUT_ARG_pointers,
    (GDBusAnnotationInfo **) &_egdbus_store_ms_method_get_folder_annotation_info_pointers
  },
  "handle-get-folder"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_get_folder_info_IN_ARG_full_name =
{
  {
    -1,
    "full_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_get_folder_info_IN_ARG_flags =
{
  {
    -1,
    "flags",
    "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_get_folder_info_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_get_folder_info_IN_ARG_full_name,
  &_egdbus_store_ms_method_info_get_folder_info_IN_ARG_flags,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_get_folder_info_OUT_ARG_infos =
{
  {
    -1,
    "infos",
    "a(sssuii)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_get_folder_info_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_get_folder_info_OUT_ARG_infos,
  NULL
};

static const GDBusAnnotationInfo _egdbus_store_ms_method_get_folder_info_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.CSymbol",
  "impl_Mail_Store_getFolderInfo",
  NULL
};

static const GDBusAnnotationInfo _egdbus_store_ms_method_get_folder_info_annotation_info_1 =
{
  -1,
  "org.freedesktop.DBus.GLib.Async",
  "",
  NULL
};

static const GDBusAnnotationInfo * const _egdbus_store_ms_method_get_folder_info_annotation_info_pointers[] =
{
  &_egdbus_store_ms_method_get_folder_info_annotation_info_0,
  &_egdbus_store_ms_method_get_folder_info_annotation_info_1,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_get_folder_info =
{
  {
    -1,
    "getFolderInfo",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_get_folder_info_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_get_folder_info_OUT_ARG_pointers,
    (GDBusAnnotationInfo **) &_egdbus_store_ms_method_get_folder_info_annotation_info_pointers
  },
  "handle-get-folder-info"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_get_inbox_OUT_ARG_folder =
{
  {
    -1,
    "folder",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_get_inbox_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_get_inbox_OUT_ARG_folder,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_get_inbox =
{
  {
    -1,
    "getInbox",
    NULL,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_get_inbox_OUT_ARG_pointers,
    NULL
  },
  "handle-get-inbox"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_get_junk_OUT_ARG_folder =
{
  {
    -1,
    "folder",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_get_junk_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_get_junk_OUT_ARG_folder,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_get_junk =
{
  {
    -1,
    "getJunk",
    NULL,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_get_junk_OUT_ARG_pointers,
    NULL
  },
  "handle-get-junk"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_get_trash_OUT_ARG_folder =
{
  {
    -1,
    "folder",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_get_trash_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_get_trash_OUT_ARG_folder,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_get_trash =
{
  {
    -1,
    "getTrash",
    NULL,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_get_trash_OUT_ARG_pointers,
    NULL
  },
  "handle-get-trash"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_create_folder_IN_ARG_parent_name =
{
  {
    -1,
    "parent_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_create_folder_IN_ARG_folder_name =
{
  {
    -1,
    "folder_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_create_folder_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_create_folder_IN_ARG_parent_name,
  &_egdbus_store_ms_method_info_create_folder_IN_ARG_folder_name,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_create_folder_OUT_ARG_info =
{
  {
    -1,
    "info",
    "a(sssuii)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_create_folder_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_create_folder_OUT_ARG_info,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_create_folder =
{
  {
    -1,
    "createFolder",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_create_folder_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_create_folder_OUT_ARG_pointers,
    NULL
  },
  "handle-create-folder"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_delete_folder_IN_ARG_folder_name =
{
  {
    -1,
    "folder_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_delete_folder_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_delete_folder_IN_ARG_folder_name,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_delete_folder_OUT_ARG_success =
{
  {
    -1,
    "success",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_delete_folder_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_delete_folder_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_delete_folder =
{
  {
    -1,
    "deleteFolder",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_delete_folder_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_delete_folder_OUT_ARG_pointers,
    NULL
  },
  "handle-delete-folder"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_rename_folder_IN_ARG_old_folder_name =
{
  {
    -1,
    "old_folder_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_rename_folder_IN_ARG_new_folder_name =
{
  {
    -1,
    "new_folder_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_rename_folder_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_rename_folder_IN_ARG_old_folder_name,
  &_egdbus_store_ms_method_info_rename_folder_IN_ARG_new_folder_name,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_rename_folder_OUT_ARG_success =
{
  {
    -1,
    "success",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_rename_folder_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_rename_folder_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_rename_folder =
{
  {
    -1,
    "renameFolder",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_rename_folder_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_rename_folder_OUT_ARG_pointers,
    NULL
  },
  "handle-rename-folder"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_supports_subscriptions_OUT_ARG_success =
{
  {
    -1,
    "success",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_supports_subscriptions_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_supports_subscriptions_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_supports_subscriptions =
{
  {
    -1,
    "supportsSubscriptions",
    NULL,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_supports_subscriptions_OUT_ARG_pointers,
    NULL
  },
  "handle-supports-subscriptions"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_is_folder_subscribed_IN_ARG_folder_name =
{
  {
    -1,
    "folder_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_is_folder_subscribed_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_is_folder_subscribed_IN_ARG_folder_name,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_is_folder_subscribed_OUT_ARG_success =
{
  {
    -1,
    "success",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_is_folder_subscribed_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_is_folder_subscribed_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_is_folder_subscribed =
{
  {
    -1,
    "isFolderSubscribed",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_is_folder_subscribed_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_is_folder_subscribed_OUT_ARG_pointers,
    NULL
  },
  "handle-is-folder-subscribed"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_subscribe_folder_IN_ARG_folder_name =
{
  {
    -1,
    "folder_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_subscribe_folder_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_subscribe_folder_IN_ARG_folder_name,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_subscribe_folder_OUT_ARG_success =
{
  {
    -1,
    "success",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_subscribe_folder_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_subscribe_folder_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_subscribe_folder =
{
  {
    -1,
    "subscribeFolder",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_subscribe_folder_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_subscribe_folder_OUT_ARG_pointers,
    NULL
  },
  "handle-subscribe-folder"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_unsubscribe_folder_IN_ARG_folder_name =
{
  {
    -1,
    "folder_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_unsubscribe_folder_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_unsubscribe_folder_IN_ARG_folder_name,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_unsubscribe_folder_OUT_ARG_success =
{
  {
    -1,
    "success",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_unsubscribe_folder_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_unsubscribe_folder_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_unsubscribe_folder =
{
  {
    -1,
    "unsubscribeFolder",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_unsubscribe_folder_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_unsubscribe_folder_OUT_ARG_pointers,
    NULL
  },
  "handle-unsubscribe-folder"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_sync_IN_ARG_expunge =
{
  {
    -1,
    "expunge",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_sync_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_sync_IN_ARG_expunge,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_sync_OUT_ARG_success =
{
  {
    -1,
    "success",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_sync_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_sync_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_sync =
{
  {
    -1,
    "sync",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_sync_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_sync_OUT_ARG_pointers,
    NULL
  },
  "handle-sync"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_noop_OUT_ARG_success =
{
  {
    -1,
    "success",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_noop_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_noop_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_noop =
{
  {
    -1,
    "noop",
    NULL,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_noop_OUT_ARG_pointers,
    NULL
  },
  "handle-noop"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_can_refresh_folder_IN_ARG_info =
{
  {
    -1,
    "info",
    "a(sssuii)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_can_refresh_folder_IN_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_can_refresh_folder_IN_ARG_info,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_method_info_can_refresh_folder_OUT_ARG_success =
{
  {
    -1,
    "success",
    "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_method_info_can_refresh_folder_OUT_ARG_pointers[] =
{
  &_egdbus_store_ms_method_info_can_refresh_folder_OUT_ARG_success,
  NULL
};

static const _ExtendedGDBusMethodInfo _egdbus_store_ms_method_info_can_refresh_folder =
{
  {
    -1,
    "canRefreshFolder",
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_can_refresh_folder_IN_ARG_pointers,
    (GDBusArgInfo **) &_egdbus_store_ms_method_info_can_refresh_folder_OUT_ARG_pointers,
    NULL
  },
  "handle-can-refresh-folder"
};

static const _ExtendedGDBusMethodInfo * const _egdbus_store_ms_method_info_pointers[] =
{
  &_egdbus_store_ms_method_info_get_folder,
  &_egdbus_store_ms_method_info_get_folder_info,
  &_egdbus_store_ms_method_info_get_inbox,
  &_egdbus_store_ms_method_info_get_junk,
  &_egdbus_store_ms_method_info_get_trash,
  &_egdbus_store_ms_method_info_create_folder,
  &_egdbus_store_ms_method_info_delete_folder,
  &_egdbus_store_ms_method_info_rename_folder,
  &_egdbus_store_ms_method_info_supports_subscriptions,
  &_egdbus_store_ms_method_info_is_folder_subscribed,
  &_egdbus_store_ms_method_info_subscribe_folder,
  &_egdbus_store_ms_method_info_unsubscribe_folder,
  &_egdbus_store_ms_method_info_sync,
  &_egdbus_store_ms_method_info_noop,
  &_egdbus_store_ms_method_info_can_refresh_folder,
  NULL
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_signal_info_folder_opened_ARG_folder =
{
  {
    -1,
    "folder",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_signal_info_folder_opened_ARG_pointers[] =
{
  &_egdbus_store_ms_signal_info_folder_opened_ARG_folder,
  NULL
};

static const _ExtendedGDBusSignalInfo _egdbus_store_ms_signal_info_folder_opened =
{
  {
    -1,
    "FolderOpened",
    (GDBusArgInfo **) &_egdbus_store_ms_signal_info_folder_opened_ARG_pointers,
    NULL
  },
  "folder-opened"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_signal_info_folder_created_ARG_info =
{
  {
    -1,
    "info",
    "a(sssuii)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_signal_info_folder_created_ARG_pointers[] =
{
  &_egdbus_store_ms_signal_info_folder_created_ARG_info,
  NULL
};

static const _ExtendedGDBusSignalInfo _egdbus_store_ms_signal_info_folder_created =
{
  {
    -1,
    "FolderCreated",
    (GDBusArgInfo **) &_egdbus_store_ms_signal_info_folder_created_ARG_pointers,
    NULL
  },
  "folder-created"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_signal_info_folder_deleted_ARG_info =
{
  {
    -1,
    "info",
    "a(sssuii)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_signal_info_folder_deleted_ARG_pointers[] =
{
  &_egdbus_store_ms_signal_info_folder_deleted_ARG_info,
  NULL
};

static const _ExtendedGDBusSignalInfo _egdbus_store_ms_signal_info_folder_deleted =
{
  {
    -1,
    "FolderDeleted",
    (GDBusArgInfo **) &_egdbus_store_ms_signal_info_folder_deleted_ARG_pointers,
    NULL
  },
  "folder-deleted"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_signal_info_folder_renamed_ARG_old_name =
{
  {
    -1,
    "old_name",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_signal_info_folder_renamed_ARG_info =
{
  {
    -1,
    "info",
    "a(sssuii)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_signal_info_folder_renamed_ARG_pointers[] =
{
  &_egdbus_store_ms_signal_info_folder_renamed_ARG_old_name,
  &_egdbus_store_ms_signal_info_folder_renamed_ARG_info,
  NULL
};

static const _ExtendedGDBusSignalInfo _egdbus_store_ms_signal_info_folder_renamed =
{
  {
    -1,
    "FolderRenamed",
    (GDBusArgInfo **) &_egdbus_store_ms_signal_info_folder_renamed_ARG_pointers,
    NULL
  },
  "folder-renamed"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_signal_info_folder_subscribed_ARG_info =
{
  {
    -1,
    "info",
    "a(sssuii)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_signal_info_folder_subscribed_ARG_pointers[] =
{
  &_egdbus_store_ms_signal_info_folder_subscribed_ARG_info,
  NULL
};

static const _ExtendedGDBusSignalInfo _egdbus_store_ms_signal_info_folder_subscribed =
{
  {
    -1,
    "FolderSubscribed",
    (GDBusArgInfo **) &_egdbus_store_ms_signal_info_folder_subscribed_ARG_pointers,
    NULL
  },
  "folder-subscribed"
};

static const _ExtendedGDBusArgInfo _egdbus_store_ms_signal_info_folder_unsubscribed_ARG_info =
{
  {
    -1,
    "info",
    "a(sssuii)",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _egdbus_store_ms_signal_info_folder_unsubscribed_ARG_pointers[] =
{
  &_egdbus_store_ms_signal_info_folder_unsubscribed_ARG_info,
  NULL
};

static const _ExtendedGDBusSignalInfo _egdbus_store_ms_signal_info_folder_unsubscribed =
{
  {
    -1,
    "FolderUnsubscribed",
    (GDBusArgInfo **) &_egdbus_store_ms_signal_info_folder_unsubscribed_ARG_pointers,
    NULL
  },
  "folder-unsubscribed"
};

static const _ExtendedGDBusSignalInfo * const _egdbus_store_ms_signal_info_pointers[] =
{
  &_egdbus_store_ms_signal_info_folder_opened,
  &_egdbus_store_ms_signal_info_folder_created,
  &_egdbus_store_ms_signal_info_folder_deleted,
  &_egdbus_store_ms_signal_info_folder_renamed,
  &_egdbus_store_ms_signal_info_folder_subscribed,
  &_egdbus_store_ms_signal_info_folder_unsubscribed,
  NULL
};

static const GDBusAnnotationInfo _egdbus_store_ms_annotation_info_0 =
{
  -1,
  "org.freedesktop.DBus.GLib.CSymbol",
  "EMailDataStore",
  NULL
};

static const GDBusAnnotationInfo * const _egdbus_store_ms_annotation_info_pointers[] =
{
  &_egdbus_store_ms_annotation_info_0,
  NULL
};

static const GDBusInterfaceInfo _egdbus_store_ms_interface_info =
{
  -1,
  "org.gnome.evolution.dataserver.mail.Store",
  (GDBusMethodInfo **) &_egdbus_store_ms_method_info_pointers,
  (GDBusSignalInfo **) &_egdbus_store_ms_signal_info_pointers,
  NULL,
  (GDBusAnnotationInfo **) &_egdbus_store_ms_annotation_info_pointers
};


GDBusInterfaceInfo *
egdbus_store_ms_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_egdbus_store_ms_interface_info;
}



static void
egdbus_store_ms_default_init (EGdbusStoreMSIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  g_signal_new ("handle-get-folder",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_get_folder),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  g_signal_new ("handle-get-folder-info",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_get_folder_info),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_UINT);

  g_signal_new ("handle-get-inbox",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_get_inbox),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  g_signal_new ("handle-get-junk",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_get_junk),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  g_signal_new ("handle-get-trash",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_get_trash),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  g_signal_new ("handle-create-folder",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_create_folder),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

  g_signal_new ("handle-delete-folder",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_delete_folder),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  g_signal_new ("handle-rename-folder",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_rename_folder),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

  g_signal_new ("handle-supports-subscriptions",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_supports_subscriptions),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  g_signal_new ("handle-is-folder-subscribed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_is_folder_subscribed),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  g_signal_new ("handle-subscribe-folder",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_subscribe_folder),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  g_signal_new ("handle-unsubscribe-folder",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_unsubscribe_folder),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  g_signal_new ("handle-sync",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_sync),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_BOOLEAN);

  g_signal_new ("handle-noop",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_noop),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  g_signal_new ("handle-can-refresh-folder",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, handle_can_refresh_folder),
    g_signal_accumulator_true_handled,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

  /* GObject signals for received D-Bus signals: */
  g_signal_new ("folder-opened",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, folder_opened),
    NULL,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  g_signal_new ("folder-created",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, folder_created),
    NULL,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

  g_signal_new ("folder-deleted",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, folder_deleted),
    NULL,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

  g_signal_new ("folder-renamed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, folder_renamed),
    NULL,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_STRING, G_TYPE_VARIANT);

  g_signal_new ("folder-subscribed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, folder_subscribed),
    NULL,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

  g_signal_new ("folder-unsubscribed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EGdbusStoreMSIface, folder_unsubscribed),
    NULL,
    NULL,
    _cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

}

typedef EGdbusStoreMSIface EGdbusStoreMSInterface;
#define egdbus_store_ms_get_type egdbus_store_ms_get_gtype
G_DEFINE_INTERFACE (EGdbusStoreMS, egdbus_store_ms, G_TYPE_OBJECT);
#undef egdbus_store_ms_get_type

void
egdbus_store_ms_emit_folder_opened (
    EGdbusStoreMS *object,
    const gchar *folder)
{
  g_signal_emit_by_name (object, "folder-opened", folder);
}

void
egdbus_store_ms_emit_folder_created (
    EGdbusStoreMS *object,
    GVariant *info)
{
  g_signal_emit_by_name (object, "folder-created", info);
}

void
egdbus_store_ms_emit_folder_deleted (
    EGdbusStoreMS *object,
    GVariant *info)
{
  g_signal_emit_by_name (object, "folder-deleted", info);
}

void
egdbus_store_ms_emit_folder_renamed (
    EGdbusStoreMS *object,
    const gchar *old_name,
    GVariant *info)
{
  g_signal_emit_by_name (object, "folder-renamed", old_name, info);
}

void
egdbus_store_ms_emit_folder_subscribed (
    EGdbusStoreMS *object,
    GVariant *info)
{
  g_signal_emit_by_name (object, "folder-subscribed", info);
}

void
egdbus_store_ms_emit_folder_unsubscribed (
    EGdbusStoreMS *object,
    GVariant *info)
{
  g_signal_emit_by_name (object, "folder-unsubscribed", info);
}

void
egdbus_store_ms_call_get_folder (
    EGdbusStoreMS *proxy,
    const gchar *full_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "getFolder",
    g_variant_new ("(s)",
                   full_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_get_folder_finish (
    EGdbusStoreMS *proxy,
    gchar **out_folder,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_folder);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_get_folder_sync (
    EGdbusStoreMS *proxy,
    const gchar *full_name,
    gchar **out_folder,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "getFolder",
    g_variant_new ("(s)",
                   full_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_folder);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_get_folder_info (
    EGdbusStoreMS *proxy,
    const gchar *full_name,
    guint flags,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "getFolderInfo",
    g_variant_new ("(su)",
                   full_name,
                   flags),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_get_folder_info_finish (
    EGdbusStoreMS *proxy,
    GVariant **out_infos,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(sssuii))",
                 out_infos);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_get_folder_info_sync (
    EGdbusStoreMS *proxy,
    const gchar *full_name,
    guint flags,
    GVariant **out_infos,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "getFolderInfo",
    g_variant_new ("(su)",
                   full_name,
                   flags),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(sssuii))",
                 out_infos);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_get_inbox (
    EGdbusStoreMS *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "getInbox",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_get_inbox_finish (
    EGdbusStoreMS *proxy,
    gchar **out_folder,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_folder);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_get_inbox_sync (
    EGdbusStoreMS *proxy,
    gchar **out_folder,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "getInbox",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_folder);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_get_junk (
    EGdbusStoreMS *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "getJunk",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_get_junk_finish (
    EGdbusStoreMS *proxy,
    gchar **out_folder,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_folder);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_get_junk_sync (
    EGdbusStoreMS *proxy,
    gchar **out_folder,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "getJunk",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_folder);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_get_trash (
    EGdbusStoreMS *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "getTrash",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_get_trash_finish (
    EGdbusStoreMS *proxy,
    gchar **out_folder,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_folder);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_get_trash_sync (
    EGdbusStoreMS *proxy,
    gchar **out_folder,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "getTrash",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_folder);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_create_folder (
    EGdbusStoreMS *proxy,
    const gchar *parent_name,
    const gchar *folder_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "createFolder",
    g_variant_new ("(ss)",
                   parent_name,
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_create_folder_finish (
    EGdbusStoreMS *proxy,
    GVariant **out_info,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(sssuii))",
                 out_info);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_create_folder_sync (
    EGdbusStoreMS *proxy,
    const gchar *parent_name,
    const gchar *folder_name,
    GVariant **out_info,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "createFolder",
    g_variant_new ("(ss)",
                   parent_name,
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a(sssuii))",
                 out_info);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_delete_folder (
    EGdbusStoreMS *proxy,
    const gchar *folder_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "deleteFolder",
    g_variant_new ("(s)",
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_delete_folder_finish (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_delete_folder_sync (
    EGdbusStoreMS *proxy,
    const gchar *folder_name,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "deleteFolder",
    g_variant_new ("(s)",
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_rename_folder (
    EGdbusStoreMS *proxy,
    const gchar *old_folder_name,
    const gchar *new_folder_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "renameFolder",
    g_variant_new ("(ss)",
                   old_folder_name,
                   new_folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_rename_folder_finish (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_rename_folder_sync (
    EGdbusStoreMS *proxy,
    const gchar *old_folder_name,
    const gchar *new_folder_name,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "renameFolder",
    g_variant_new ("(ss)",
                   old_folder_name,
                   new_folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_supports_subscriptions (
    EGdbusStoreMS *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "supportsSubscriptions",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_supports_subscriptions_finish (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_supports_subscriptions_sync (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "supportsSubscriptions",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_is_folder_subscribed (
    EGdbusStoreMS *proxy,
    const gchar *folder_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "isFolderSubscribed",
    g_variant_new ("(s)",
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_is_folder_subscribed_finish (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_is_folder_subscribed_sync (
    EGdbusStoreMS *proxy,
    const gchar *folder_name,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "isFolderSubscribed",
    g_variant_new ("(s)",
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_subscribe_folder (
    EGdbusStoreMS *proxy,
    const gchar *folder_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "subscribeFolder",
    g_variant_new ("(s)",
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_subscribe_folder_finish (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_subscribe_folder_sync (
    EGdbusStoreMS *proxy,
    const gchar *folder_name,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "subscribeFolder",
    g_variant_new ("(s)",
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_unsubscribe_folder (
    EGdbusStoreMS *proxy,
    const gchar *folder_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "unsubscribeFolder",
    g_variant_new ("(s)",
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_unsubscribe_folder_finish (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_unsubscribe_folder_sync (
    EGdbusStoreMS *proxy,
    const gchar *folder_name,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "unsubscribeFolder",
    g_variant_new ("(s)",
                   folder_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_sync (
    EGdbusStoreMS *proxy,
    gboolean expunge,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "sync",
    g_variant_new ("(b)",
                   expunge),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_sync_finish (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_sync_sync (
    EGdbusStoreMS *proxy,
    gboolean expunge,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "sync",
    g_variant_new ("(b)",
                   expunge),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_noop (
    EGdbusStoreMS *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "noop",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_noop_finish (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_noop_sync (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "noop",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_call_can_refresh_folder (
    EGdbusStoreMS *proxy,
    GVariant *info,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "canRefreshFolder",
    g_variant_new ("(@a(sssuii))",
                   info),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

gboolean
egdbus_store_ms_call_can_refresh_folder_finish (
    EGdbusStoreMS *proxy,
    gboolean *out_success,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

gboolean
egdbus_store_ms_call_can_refresh_folder_sync (
    EGdbusStoreMS *proxy,
    GVariant *info,
    gboolean *out_success,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "canRefreshFolder",
    g_variant_new ("(@a(sssuii))",
                   info),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(b)",
                 out_success);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

void
egdbus_store_ms_complete_get_folder (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    const gchar *folder)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   folder));
}

void
egdbus_store_ms_complete_get_folder_info (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    GVariant *infos)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a(sssuii))",
                   infos));
}

void
egdbus_store_ms_complete_get_inbox (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    const gchar *folder)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   folder));
}

void
egdbus_store_ms_complete_get_junk (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    const gchar *folder)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   folder));
}

void
egdbus_store_ms_complete_get_trash (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    const gchar *folder)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   folder));
}

void
egdbus_store_ms_complete_create_folder (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    GVariant *info)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a(sssuii))",
                   info));
}

void
egdbus_store_ms_complete_delete_folder (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

void
egdbus_store_ms_complete_rename_folder (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

void
egdbus_store_ms_complete_supports_subscriptions (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

void
egdbus_store_ms_complete_is_folder_subscribed (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

void
egdbus_store_ms_complete_subscribe_folder (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

void
egdbus_store_ms_complete_unsubscribe_folder (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

void
egdbus_store_ms_complete_sync (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

void
egdbus_store_ms_complete_noop (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

void
egdbus_store_ms_complete_can_refresh_folder (
    EGdbusStoreMS *object,
    GDBusMethodInvocation *invocation,
    gboolean success)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(b)",
                   success));
}

/* ------------------------------------------------------------------------ */

static void
egdbus_store_ms_proxy_iface_init (EGdbusStoreMSIface *iface)
{
}

#define egdbus_store_ms_proxy_get_type egdbus_store_ms_proxy_get_gtype
G_DEFINE_TYPE_WITH_CODE (EGdbusStoreMSProxy, egdbus_store_ms_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (EGDBUS_STORE_TYPE_MS, egdbus_store_ms_proxy_iface_init));
#undef egdbus_store_ms_proxy_get_type

static void
egdbus_store_ms_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
egdbus_store_ms_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
egdbus_store_ms_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_egdbus_store_ms_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], EGDBUS_STORE_TYPE_MS);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, EGDBUS_STORE_TYPE_MS);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
egdbus_store_ms_proxy_g_properties_changed (GDBusProxy *proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_egdbus_store_ms_interface_info, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_egdbus_store_ms_interface_info, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
egdbus_store_ms_proxy_init (EGdbusStoreMSProxy *proxy)
{
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), egdbus_store_ms_interface_info ());
}

static void
egdbus_store_ms_proxy_class_init (EGdbusStoreMSProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->get_property = egdbus_store_ms_proxy_get_property;
  gobject_class->set_property = egdbus_store_ms_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = egdbus_store_ms_proxy_g_signal;
  proxy_class->g_properties_changed = egdbus_store_ms_proxy_g_properties_changed;

}
void
egdbus_store_ms_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (EGDBUS_STORE_TYPE_MS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.evolution.dataserver.mail.Store", NULL);
}

EGdbusStoreMS *
egdbus_store_ms_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return EGDBUS_STORE_MS (ret);
  else
    return NULL;
}

EGdbusStoreMS *
egdbus_store_ms_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (EGDBUS_STORE_TYPE_MS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.evolution.dataserver.mail.Store", NULL);
  if (ret != NULL)
    return EGDBUS_STORE_MS (ret);
  else
    return NULL;
}


void
egdbus_store_ms_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (EGDBUS_STORE_TYPE_MS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.evolution.dataserver.mail.Store", NULL);
}

EGdbusStoreMS *
egdbus_store_ms_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return EGDBUS_STORE_MS (ret);
  else
    return NULL;
}

EGdbusStoreMS *
egdbus_store_ms_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (EGDBUS_STORE_TYPE_MS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.evolution.dataserver.mail.Store", NULL);
  if (ret != NULL)
    return EGDBUS_STORE_MS (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

struct _EGdbusStoreMSStubPrivate
{
  GValueArray *properties;
  GDBusObject *object;
  GDBusInterfaceFlags flags;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GDBusConnection *connection;
  gchar *object_path;
  GMainContext *context;
};

static void
_egdbus_store_ms_stub_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  GValue return_value = {0};
  info = (_ExtendedGDBusMethodInfo *) g_dbus_interface_info_lookup_method ((GDBusInterfaceInfo *) &_egdbus_store_ms_interface_info, method_name);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 2);
  g_value_init (&paramv[0], EGDBUS_STORE_TYPE_MS);
  g_value_set_object (&paramv[0], stub);
  g_value_init (&paramv[1], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[1], invocation);
  g_variant_iter_init (&iter, parameters);
  n = 2;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - 2];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, EGDBUS_STORE_TYPE_MS);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + 2; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_egdbus_store_ms_stub_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_egdbus_store_ms_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (stub), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (stub), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_egdbus_store_ms_stub_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_egdbus_store_ms_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (stub), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (stub), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _egdbus_store_ms_stub_vtable =
{
  _egdbus_store_ms_stub_handle_method_call,
  _egdbus_store_ms_stub_handle_get_property,
  _egdbus_store_ms_stub_handle_set_property
};

static GDBusInterfaceInfo *
egdbus_store_ms_stub_dbus_interface_get_info (GDBusInterface *interface)
{
  return egdbus_store_ms_interface_info ();
}

static GVariant *
egdbus_store_ms_stub_dbus_interface_get_properties (GDBusInterface *interface)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (interface);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_egdbus_store_ms_interface_info.properties == NULL)
    goto out;
  for (n = 0; _egdbus_store_ms_interface_info.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _egdbus_store_ms_interface_info.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _egdbus_store_ms_stub_handle_get_property (stub->priv->connection, NULL, stub->priv->object_path, "org.gnome.evolution.dataserver.mail.Store", info->name, NULL, stub);
          if (value != NULL)
            {
              if (g_variant_is_floating (value))
                g_variant_ref_sink (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
egdbus_store_ms_stub_dbus_interface_flush (GDBusInterface *interface)
{
}

static void
_egdbus_store_ms_on_object_unregistered (EGdbusStoreMSStub *stub)
{
  stub->priv->connection = NULL;
  g_free (stub->priv->object_path);
  stub->priv->object_path = NULL;
}

static guint
egdbus_store_ms_stub_dbus_interface_register_object (GDBusInterface *interface,  GDBusConnection *connection,
  const gchar *object_path,
  GError **error)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (interface);
  stub->priv->connection = connection;
  stub->priv->object_path = g_strdup (object_path);
  stub->priv->context = g_main_context_get_thread_default ();
  if (stub->priv->context != NULL)
    g_main_context_ref (stub->priv->context);
  return g_dbus_connection_register_object (connection, object_path, egdbus_store_ms_interface_info (), &_egdbus_store_ms_stub_vtable, stub, (GDestroyNotify) _egdbus_store_ms_on_object_unregistered, error);
}

static GDBusObject *
egdbus_store_ms_stub_dbus_interface_get_object (GDBusInterface *interface)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (interface);
  return stub->priv->object != NULL ? g_object_ref (stub->priv->object) : NULL;
}

static void
egdbus_store_ms_stub_dbus_interface_set_object (GDBusInterface *interface,  GDBusObject *object)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (interface);
  stub->priv->object = object;
}

static GDBusInterfaceFlags
egdbus_store_ms_stub_dbus_interface_get_flags (GDBusInterface *interface)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (interface);
  return stub->priv->flags;
}

static void
egdbus_store_ms_stub_dbus_interface_set_flags (GDBusInterface *interface,  GDBusInterfaceFlags flags)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (interface);
  stub->priv->flags = flags;
}

static void
_egdbus_store_ms_on_signal_folder_opened (
    EGdbusStoreMS *object,
    const gchar *folder)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (object);
  if (stub->priv->connection == NULL)
    return;
  g_dbus_connection_emit_signal (stub->priv->connection,
    NULL, stub->priv->object_path, "org.gnome.evolution.dataserver.mail.Store", "FolderOpened",
    g_variant_new ("(o)",
                   folder), NULL);
}

static void
_egdbus_store_ms_on_signal_folder_created (
    EGdbusStoreMS *object,
    GVariant *info)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (object);
  if (stub->priv->connection == NULL)
    return;
  g_dbus_connection_emit_signal (stub->priv->connection,
    NULL, stub->priv->object_path, "org.gnome.evolution.dataserver.mail.Store", "FolderCreated",
    g_variant_new ("(@a(sssuii))",
                   info), NULL);
}

static void
_egdbus_store_ms_on_signal_folder_deleted (
    EGdbusStoreMS *object,
    GVariant *info)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (object);
  if (stub->priv->connection == NULL)
    return;
  g_dbus_connection_emit_signal (stub->priv->connection,
    NULL, stub->priv->object_path, "org.gnome.evolution.dataserver.mail.Store", "FolderDeleted",
    g_variant_new ("(@a(sssuii))",
                   info), NULL);
}

static void
_egdbus_store_ms_on_signal_folder_renamed (
    EGdbusStoreMS *object,
    const gchar *old_name,
    GVariant *info)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (object);
  if (stub->priv->connection == NULL)
    return;
  g_dbus_connection_emit_signal (stub->priv->connection,
    NULL, stub->priv->object_path, "org.gnome.evolution.dataserver.mail.Store", "FolderRenamed",
    g_variant_new ("(s@a(sssuii))",
                   old_name,
                   info), NULL);
}

static void
_egdbus_store_ms_on_signal_folder_subscribed (
    EGdbusStoreMS *object,
    GVariant *info)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (object);
  if (stub->priv->connection == NULL)
    return;
  g_dbus_connection_emit_signal (stub->priv->connection,
    NULL, stub->priv->object_path, "org.gnome.evolution.dataserver.mail.Store", "FolderSubscribed",
    g_variant_new ("(@a(sssuii))",
                   info), NULL);
}

static void
_egdbus_store_ms_on_signal_folder_unsubscribed (
    EGdbusStoreMS *object,
    GVariant *info)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (object);
  if (stub->priv->connection == NULL)
    return;
  g_dbus_connection_emit_signal (stub->priv->connection,
    NULL, stub->priv->object_path, "org.gnome.evolution.dataserver.mail.Store", "FolderUnsubscribed",
    g_variant_new ("(@a(sssuii))",
                   info), NULL);
}

static void
egdbus_store_ms_stub_iface_init (EGdbusStoreMSIface *iface)
{
  iface->folder_opened = _egdbus_store_ms_on_signal_folder_opened;
  iface->folder_created = _egdbus_store_ms_on_signal_folder_created;
  iface->folder_deleted = _egdbus_store_ms_on_signal_folder_deleted;
  iface->folder_renamed = _egdbus_store_ms_on_signal_folder_renamed;
  iface->folder_subscribed = _egdbus_store_ms_on_signal_folder_subscribed;
  iface->folder_unsubscribed = _egdbus_store_ms_on_signal_folder_unsubscribed;
}

static void
egdbus_store_ms_stub_dbus_iface_init (GDBusInterfaceIface *iface)
{
  iface->get_info = egdbus_store_ms_stub_dbus_interface_get_info;
  iface->get_properties = egdbus_store_ms_stub_dbus_interface_get_properties;
  iface->flush = egdbus_store_ms_stub_dbus_interface_flush;
  iface->register_object = egdbus_store_ms_stub_dbus_interface_register_object;
  iface->get_object = egdbus_store_ms_stub_dbus_interface_get_object;
  iface->set_object = egdbus_store_ms_stub_dbus_interface_set_object;
  iface->get_flags = egdbus_store_ms_stub_dbus_interface_get_flags;
  iface->set_flags = egdbus_store_ms_stub_dbus_interface_set_flags;
}

#define egdbus_store_ms_stub_get_type egdbus_store_ms_stub_get_gtype
G_DEFINE_TYPE_WITH_CODE (EGdbusStoreMSStub, egdbus_store_ms_stub, G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (EGDBUS_STORE_TYPE_MS, egdbus_store_ms_stub_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_INTERFACE, egdbus_store_ms_stub_dbus_iface_init));
#undef egdbus_store_ms_stub_get_type

static void
egdbus_store_ms_stub_finalize (GObject *object)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (object);
  g_list_foreach (stub->priv->changed_properties, (GFunc) _changed_property_free, NULL);
  g_list_free (stub->priv->changed_properties);
  if (stub->priv->changed_properties_idle_source != NULL)
    g_source_destroy (stub->priv->changed_properties_idle_source);
  if (stub->priv->context != NULL)
    g_main_context_unref (stub->priv->context);
  G_OBJECT_CLASS (egdbus_store_ms_stub_parent_class)->finalize (object);
}

static void
egdbus_store_ms_stub_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  EGdbusStoreMSStub *stub = EGDBUS_STORE_MS_STUB (object);
  g_assert (prop_id - 1 >= 0 && prop_id - 1 < 0);
  g_value_copy (&stub->priv->properties->values[prop_id - 1], value);
}

static void
egdbus_store_ms_stub_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
egdbus_store_ms_stub_init (EGdbusStoreMSStub *stub)
{
  stub->priv = G_TYPE_INSTANCE_GET_PRIVATE (stub, EGDBUS_STORE_TYPE_MS_STUB, EGdbusStoreMSStubPrivate);
}

static void
egdbus_store_ms_stub_class_init (EGdbusStoreMSStubClass *klass)
{
  GObjectClass *gobject_class;

  g_type_class_add_private (klass, sizeof (EGdbusStoreMSStubPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = egdbus_store_ms_stub_finalize;
  gobject_class->get_property = egdbus_store_ms_stub_get_property;
  gobject_class->set_property = egdbus_store_ms_stub_set_property;

}

EGdbusStoreMS *
egdbus_store_ms_stub_new (void)
{
  return EGDBUS_STORE_MS (g_object_new (EGDBUS_STORE_TYPE_MS_STUB, NULL));
}

/* ------------------------------------------------------------------------
 * Code for proxy manager
 * ------------------------------------------------------------------------
 */

/* ------------------------------------------------------------------------ */

#define egdbus_store_proxy_manager_get_type egdbus_store_proxy_manager_get_gtype
G_DEFINE_TYPE (EGdbusStoreProxyManager, egdbus_store_proxy_manager, G_TYPE_DBUS_PROXY_MANAGER);
#undef egdbus_store_proxy_manager_get_type

static void
egdbus_store_proxy_manager_init (EGdbusStoreProxyManager *manager)
{
}

static void
egdbus_store_proxy_manager_class_init (EGdbusStoreProxyManagerClass *klass)
{
}

static GType
_egdbus_store_proxy_manager_get_proxy_type_func (GDBusProxyManager *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data)
{
  GType ret;
  ret = G_TYPE_DBUS_PROXY;
  if (FALSE)
    ;
  else if (g_strcmp0 (interface_name, "org.gnome.evolution.dataserver.mail.Store") == 0)
    ret = EGDBUS_STORE_TYPE_MS_PROXY;
  return ret;
}

GDBusProxyTypeFunc
egdbus_store_proxy_manager_get_proxy_type_func (void)
{
  return _egdbus_store_proxy_manager_get_proxy_type_func;
}

void
egdbus_store_proxy_manager_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (EGDBUS_STORE_TYPE_PROXY_MANAGER, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", _egdbus_store_proxy_manager_get_proxy_type_func, NULL);
}

GDBusProxyManager *
egdbus_store_proxy_manager_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_PROXY_MANAGER (ret);
  else
    return NULL;
}

GDBusProxyManager *
egdbus_store_proxy_manager_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (EGDBUS_STORE_TYPE_PROXY_MANAGER, cancellable, error, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", _egdbus_store_proxy_manager_get_proxy_type_func, NULL);
  if (ret != NULL)
    return G_DBUS_PROXY_MANAGER (ret);
  else
    return NULL;
}


void
egdbus_store_proxy_manager_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (EGDBUS_STORE_TYPE_PROXY_MANAGER, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", _egdbus_store_proxy_manager_get_proxy_type_func, NULL);
}

GDBusProxyManager *
egdbus_store_proxy_manager_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_PROXY_MANAGER (ret);
  else
    return NULL;
}

GDBusProxyManager *
egdbus_store_proxy_manager_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (EGDBUS_STORE_TYPE_PROXY_MANAGER, cancellable, error, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", _egdbus_store_proxy_manager_get_proxy_type_func, NULL);
  if (ret != NULL)
    return G_DBUS_PROXY_MANAGER (ret);
  else
    return NULL;
}


