/* File:       e-gdbus-egdbusbookfactory.h
 *
 * GType name: EGdbusBookFactory
 * D-Bus name: org.gnome.evolution.dataserver.addressbook.BookFactory
 *
 * Generated by GDBus Binding Tool 0.1. DO NOT EDIT.
 */

#ifndef __E_GDBUS_E_GDBUS_BOOK_FACTORY_H__
#define __E_GDBUS_E_GDBUS_BOOK_FACTORY_H__

#include <gio/gio.h>

#include "e-gdbus-typemappers.h"
G_BEGIN_DECLS

#define E_GDBUS_TYPE_BOOK_FACTORY         (e_gdbus_book_factory_get_type ())
#define E_GDBUS_BOOK_FACTORY(o)           (G_TYPE_CHECK_INSTANCE_CAST ((o), E_GDBUS_TYPE_BOOK_FACTORY, EGdbusBookFactory))
#define E_GDBUS_IS_BOOK_FACTORY(o)        (G_TYPE_CHECK_INSTANCE_TYPE ((o), E_GDBUS_TYPE_BOOK_FACTORY))
#define E_GDBUS_BOOK_FACTORY_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE((o), E_GDBUS_TYPE_BOOK_FACTORY, EGdbusBookFactoryIface))

/**
 * EGdbusBookFactory:
 *
 * Opaque type representing a proxy or an exported object.
 */
typedef struct _EGdbusBookFactory EGdbusBookFactory; /* Dummy typedef */
/**
 * EGdbusBookFactoryIface:
 * @parent_iface: The parent interface.
 * @handle_get_book: Handler for the #EGdbusBookFactory::handle-get-book signal.
 *
 * Virtual table.
 */
typedef struct _EGdbusBookFactoryIface EGdbusBookFactoryIface;

GType e_gdbus_book_factory_get_type (void) G_GNUC_CONST;

/* ---------------------------------------------------------------------- */

typedef struct _EGdbusBookFactoryProxy EGdbusBookFactoryProxy;
typedef struct _EGdbusBookFactoryProxyClass EGdbusBookFactoryProxyClass;

/**
 * EGdbusBookFactoryProxyPrivate:
 *
 * The #EGdbusBookFactoryProxyPrivate structure contains only private data.
 */
typedef struct _EGdbusBookFactoryProxyPrivate EGdbusBookFactoryProxyPrivate;

/**
 * EGdbusBookFactoryProxy:
 *
 * The #EGdbusBookFactoryProxy structure contains only private data and
 * should only be accessed using the provided API.
 */
struct _EGdbusBookFactoryProxy
{
  GDBusProxy parent_instance;
  EGdbusBookFactoryProxyPrivate *priv;
};

/**
 * EGdbusBookFactoryProxyClass:
 *
 * Class structure for #EGdbusBookFactoryProxy.
 */
struct _EGdbusBookFactoryProxyClass
{
  GDBusProxyClass parent_class;
};

#define E_GDBUS_TYPE_BOOK_FACTORY_PROXY (e_gdbus_book_factory_proxy_get_type ())
GType e_gdbus_book_factory_proxy_get_type (void) G_GNUC_CONST;

void e_gdbus_book_factory_proxy_new (GDBusConnection     *connection,
                   GDBusProxyFlags      flags,
                   const gchar         *name,
                   const gchar         *object_path,
                   GCancellable        *cancellable,
                   GAsyncReadyCallback  callback,
                   gpointer             user_data);
EGdbusBookFactory *e_gdbus_book_factory_proxy_new_finish (GAsyncResult  *res,
                        GError       **error);
EGdbusBookFactory *e_gdbus_book_factory_proxy_new_sync (GDBusConnection     *connection,
                       GDBusProxyFlags      flags,
                       const gchar         *name,
                       const gchar         *object_path,
                       GCancellable        *cancellable,
                       GError             **error);

void e_gdbus_book_factory_proxy_new_for_bus (GBusType             bus_type,
                           GDBusProxyFlags      flags,
                           const gchar         *name,
                           const gchar         *object_path,
                           GCancellable        *cancellable,
                           GAsyncReadyCallback  callback,
                           gpointer             user_data);
EGdbusBookFactory *e_gdbus_book_factory_proxy_new_for_bus_finish (GAsyncResult  *res,
                                 GError       **error);
EGdbusBookFactory *e_gdbus_book_factory_proxy_new_for_bus_sync (GBusType             bus_type,
                               GDBusProxyFlags      flags,
                               const gchar         *name,
                               const gchar         *object_path,
                               GCancellable        *cancellable,
                               GError             **error);

/* ---------------------------------------------------------------------- */

typedef struct _EGdbusBookFactoryStub EGdbusBookFactoryStub;
typedef struct _EGdbusBookFactoryStubClass EGdbusBookFactoryStubClass;

/**
 * EGdbusBookFactoryStubPrivate:
 *
 * The #EGdbusBookFactoryStubPrivate structure contains only private data.
 */
typedef struct _EGdbusBookFactoryStubPrivate EGdbusBookFactoryStubPrivate;

/**
 * EGdbusBookFactoryStub:
 *
 * The #EGdbusBookFactoryStub structure contains only private data and
 * should only be accessed using the provided API.
 */
struct _EGdbusBookFactoryStub
{
  GObject parent_instance;
  EGdbusBookFactoryStubPrivate *priv;
};

/**
 * EGdbusBookFactoryStubClass:
 *
 * Class structure for #EGdbusBookFactoryStub.
 */
struct _EGdbusBookFactoryStubClass
{
  GObjectClass parent_class;
};

#define E_GDBUS_TYPE_BOOK_FACTORY_STUB (e_gdbus_book_factory_stub_get_type ())
GType e_gdbus_book_factory_stub_get_type (void) G_GNUC_CONST;

EGdbusBookFactory *e_gdbus_book_factory_stub_new (void);

guint e_gdbus_book_factory_register_object (EGdbusBookFactory *object,
                    GDBusConnection *connection,
                    const gchar *object_path,
                    GError **error);

void e_gdbus_book_factory_drain_notify (EGdbusBookFactory *object);

const GDBusInterfaceInfo *e_gdbus_book_factory_interface_info (void) G_GNUC_CONST;

struct _EGdbusBookFactoryIface
{
  GTypeInterface parent_iface;

  /* Signal handlers for receiving D-Bus signals: */

  /* Signal handlers for handling D-Bus method calls: */
  gboolean (*handle_get_book) (
        EGdbusBookFactory *object,
        GDBusMethodInvocation *invocation,
        const gchar *in_source);
};

/* C Bindings for properties */

/* D-Bus Methods */
void e_gdbus_book_factory_call_get_book (
        EGdbusBookFactory *proxy,
        const gchar *in_source,
        GCancellable *cancellable,
        GAsyncReadyCallback callback,
        gpointer user_data);

gboolean e_gdbus_book_factory_call_get_book_finish (
        EGdbusBookFactory *proxy,
        gchar **out_path,
        GAsyncResult *res,
        GError **error);

gboolean e_gdbus_book_factory_call_get_book_sync (
        EGdbusBookFactory *proxy,
        const gchar *in_source,
        gchar **out_path,
        GCancellable *cancellable,
        GError **error);

/* D-Bus Methods Completion Helpers */
void e_gdbus_book_factory_complete_get_book (
        EGdbusBookFactory *object,
        GDBusMethodInvocation *invocation,
        const gchar *out_path);

/* D-Bus Signal Emission Helpers */

G_END_DECLS

#endif /* __E_GDBUS_E_GDBUS_BOOK_FACTORY_H__ */
