/*
 * Server interfaces.
 *
 * Copyright (C) 2000, 2001, 2002, Ximian, Inc.
 */

#include <Bonobo.idl>

module GNOME {
module Evolution {
module DataServer {
		
	interface Config {
	};

	interface InterfaceCheck : Bonobo::Unknown {
		readonly attribute string interfaceVersion;
	};


	interface Logging : Bonobo::EventSource {
		enum Level {
			Error,
			Critical,
			Warning,
			Message,
			Info,
			Debug
		};

		struct LogEvent {
			string domain;
			Level level;	
			string message;
		};

	};
};
};
};
